### ISSUE TITLE
A LWTarantool::UnknownError when receive TNT_EBIG (Buffer is too big) error from Tarantool

### ISSUE THREAD

**Issue by rikitikitav1** [0xBF/lwtarantool#1]
Getting this error when trying to make a big amount of requests with high intensity to the database and it does not have time to process them before I send another request.

Tarantool: 1.9.1, Ruby: 2.4
Trace:
```
"exception":{"name":"LWTarantool::UnknownError",
"message":"buffer is too big",
"stack_trace":["/opt/***/vendor/bundle/ruby/2.4.0/gems/lwtarantool-0.0.2/lib/lwtarantool/connection.rb:31:in `_call'",
"/opt/***/vendor/bundle/ruby/2.4.0/gems/lwtarantool-0.0.2/lib/lwtarantool/connection.rb:31:in `block in call'",
"/opt/***/vendor/bundle/ruby/2.4.0/gems/lwtarantool-0.0.2/lib/lwtarantool/connection.rb:29:in `synchronize'",
"/opt/***/vendor/bundle/ruby/2.4.0/gems/lwtarantool-0.0.2/lib/lwtarantool/connection.rb:29:in `call'"
```

**Comment by 0xBF** [comment]
Thank you for report!

It looks like an insufficient size of connection buffer. It is not a server response.
Please, try new gem version (0.0.3) and initialize connection with extra `send_buf_size` option:
```
conn = LWTarantool.new(url: '...', send_buf_size: 2**20)
```

Also you may need to handle new exception `LWTarantool::TooLargeRequestError`

**Comment by rikitikitav1** [comment]
Thank you, it works now!
