### ISSUE TITLE
Custom timeout interval on LWTarantool initialization

### ISSUE THREAD

**Issue by rikitikitav1** [0xBF/lwtarantool#3]
Hello once again!

It would be great to have an opportunity to set the custom timeout interval value in seconds when LWtarantool initializes:
```ruby
LWTarantool.new(url: '127.0.0.1:3301', timeout:1)
```
It should help with customizing tarantool connection a lot.

**Comment by 0xBF** [comment]
I add connect_timeout and open_timeout options in verion 0.0.4.

**Comment by rikitikitav1** [comment]
Thank you!
